// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-HlTxskPtDvNtPaOr23B-W1B6KlPdqNA',
    appId: '1:822941014138:web:421c0d27564cb6491543c3',
    messagingSenderId: '822941014138',
    projectId: 'tutors-3a680',
    authDomain: 'tutors-3a680.firebaseapp.com',
    storageBucket: 'tutors-3a680.firebasestorage.app',
    measurementId: 'G-9VJP2S33PV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL4NgYDeLP4Z626mcHKqf9gZnSFe2pT20',
    appId: '1:822941014138:android:f88a7aae02e3b8721543c3',
    messagingSenderId: '822941014138',
    projectId: 'tutors-3a680',
    storageBucket: 'tutors-3a680.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC07I5NruC4LN3y3jmyW31kFIyc9w-Ikg4',
    appId: '1:822941014138:ios:c8efc6d0e5f384731543c3',
    messagingSenderId: '822941014138',
    projectId: 'tutors-3a680',
    storageBucket: 'tutors-3a680.firebasestorage.app',
    iosBundleId: 'com.example.careTutors',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC07I5NruC4LN3y3jmyW31kFIyc9w-Ikg4',
    appId: '1:822941014138:ios:c8efc6d0e5f384731543c3',
    messagingSenderId: '822941014138',
    projectId: 'tutors-3a680',
    storageBucket: 'tutors-3a680.firebasestorage.app',
    iosBundleId: 'com.example.careTutors',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-HlTxskPtDvNtPaOr23B-W1B6KlPdqNA',
    appId: '1:822941014138:web:46eb6d7cefa693261543c3',
    messagingSenderId: '822941014138',
    projectId: 'tutors-3a680',
    authDomain: 'tutors-3a680.firebaseapp.com',
    storageBucket: 'tutors-3a680.firebasestorage.app',
    measurementId: 'G-QNVVFNL0CE',
  );
}
